language: rust
rust: nightly

script:
    - cargo build --features nightly
    - cargo test --features nightly
    - cargo bench --features nightly

after_success:
  
    echo "Running TestSuite " ; 

